### ISSUE TITLE
Nested Q3 Runtime Exception

### ISSUE THREAD

**Issue by pouriapirz** [pouriapirz/tpch-on-asterixdb#3]
[Query](https://github.com/pouriapirz/tpch-on-asterixdb/blob/master/queries-nested-aql/q3.aql) hits an array index out of bound in runtime.

Optimized logical plan

```
distribute result [%0->$$33]
-- DISTRIBUTE_RESULT  |UNPARTITIONED|
  exchange
  -- ONE_TO_ONE_EXCHANGE  |UNPARTITIONED|
    project ([$$33])
    -- STREAM_PROJECT  |UNPARTITIONED|
      assign [$$33] <- [function-call: asterix:closed-record-constructor, Args:[AString: {l_orderkey}, %0->$$3, AString: {revenue}, %0->$$42, AString: {o_orderdate}, %0->$$4, AString: {o_shippriority}, %0->$$5]]
      -- ASSIGN  |UNPARTITIONED|
        limit AInt64: {10}
        -- STREAM_LIMIT  |UNPARTITIONED|
          exchange
          -- SORT_MERGE_EXCHANGE [$$42(DESC), $$4(ASC) ]  |PARTITIONED|
            limit AInt64: {10}
            -- STREAM_LIMIT  |PARTITIONED|
              exchange
              -- ONE_TO_ONE_EXCHANGE  |PARTITIONED|
                order (topK: 10) (DESC, %0->$$42) (topK: 10) (ASC, %0->$$4) 
                -- STABLE_SORT [topK: 10] [$$42(DESC), $$4(ASC)]  |PARTITIONED|
                  exchange
                  -- ONE_TO_ONE_EXCHANGE  |PARTITIONED|
                    group by ([$$3 := %0->$$49]) decor ([$$4 := %0->$$50; $$5 := %0->$$51]) {
                              aggregate [$$42] <- [function-call: asterix:sum-serial, Args:[%0->$$48]]
                              -- AGGREGATE  |LOCAL|
                                nested tuple source
                                -- NESTED_TUPLE_SOURCE  |LOCAL|
                           }
                    -- EXTERNAL_GROUP_BY[$$49]  |PARTITIONED|
                      exchange
                      -- HASH_PARTITION_EXCHANGE [$$49]  |PARTITIONED|
                        group by ([$$49 := %0->$$39]) decor ([$$50 := %0->$$37; $$51 := %0->$$36]) {
                                  aggregate [$$48] <- [function-call: asterix:local-sum-serial, Args:[function-call: asterix:numeric-multiply, Args:[%0->$$46, function-call: asterix:numeric-subtract, Args:[AInt64: {1}, %0->$$47]]]]
                                  -- AGGREGATE  |LOCAL|
                                    nested tuple source
                                    -- NESTED_TUPLE_SOURCE  |LOCAL|
                               }
                        -- EXTERNAL_GROUP_BY[$$39]  |PARTITIONED|
                          exchange
                          -- ONE_TO_ONE_EXCHANGE  |PARTITIONED|
                            project ([$$36, $$37, $$39, $$46, $$47])
                            -- STREAM_PROJECT  |PARTITIONED|
                              exchange
                              -- ONE_TO_ONE_EXCHANGE  |PARTITIONED|
                                join (function-call: algebricks:eq, Args:[%0->$$38, %0->$$41])
                                -- HYBRID_HASH_JOIN [$$38][$$41]  |PARTITIONED|
                                  exchange
                                  -- ONE_TO_ONE_EXCHANGE  |PARTITIONED|
                                    project ([$$38])
                                    -- STREAM_PROJECT  |PARTITIONED|
                                      select (function-call: algebricks:eq, Args:[function-call: asterix:field-access-by-index, Args:[%0->$$0, AInt32: {6}], AString: {BUILDING}])
                                      -- STREAM_SELECT  |PARTITIONED|
                                        exchange
                                        -- ONE_TO_ONE_EXCHANGE  |PARTITIONED|
                                          data-scan []<-[$$38, $$0] <- tpch:Customer
                                          -- DATASOURCE_SCAN  |PARTITIONED|
                                            exchange
                                            -- ONE_TO_ONE_EXCHANGE  |PARTITIONED|
                                              empty-tuple-source
                                              -- EMPTY_TUPLE_SOURCE  |PARTITIONED|
                                  exchange
                                  -- HASH_PARTITION_EXCHANGE [$$41]  |PARTITIONED|
                                    project ([$$36, $$37, $$39, $$41, $$46, $$47])
                                    -- STREAM_PROJECT  |PARTITIONED|
                                      select (function-call: algebricks:gt, Args:[function-call: asterix:field-access-by-index, Args:[%0->$$6, AInt32: {9}], AString: {1995-03-15}])
                                      -- STREAM_SELECT  |PARTITIONED|
                                        assign [$$47, $$46] <- [function-call: asterix:field-access-by-index, Args:[%0->$$6, AInt32: {5}], function-call: asterix:field-access-by-index, Args:[%0->$$6, AInt32: {4}]]
                                        -- ASSIGN  |PARTITIONED|
                                          project ([$$36, $$37, $$6, $$39, $$41])
                                          -- STREAM_PROJECT  |PARTITIONED|
                                            unnest $$6 <- function-call: asterix:scan-collection, Args:[%0->$$44]
                                            -- UNNEST  |PARTITIONED|
                                              select (function-call: algebricks:lt, Args:[%0->$$37, AString: {1995-03-15}])
                                              -- STREAM_SELECT  |PARTITIONED|
                                                project ([$$36, $$37, $$39, $$41, $$44])
                                                -- STREAM_PROJECT  |PARTITIONED|
                                                  assign [$$36, $$41, $$37, $$44] <- [function-call: asterix:field-access-by-index, Args:[%0->$$1, AInt32: {7}], function-call: asterix:field-access-by-index, Args:[%0->$$1, AInt32: {1}], function-call: asterix:field-access-by-index, Args:[%0->$$1, AInt32: {4}], function-call: asterix:field-access-by-index, Args:[%0->$$1, AInt32: {9}]]
                                                  -- ASSIGN  |PARTITIONED|
                                                    exchange
                                                    -- ONE_TO_ONE_EXCHANGE  |PARTITIONED|
                                                      data-scan []<-[$$39, $$1] <- tpch:NestedOrders
                                                      -- DATASOURCE_SCAN  |PARTITIONED|
                                                        exchange
                                                        -- ONE_TO_ONE_EXCHANGE  |PARTITIONED|
                                                          empty-tuple-source
                                                          -- EMPTY_TUPLE_SOURCE  |PARTITIONED|
```

**CC logs**

```
SEVERE: Job failed on account of:
HYR0002: org.apache.hyracks.api.exceptions.HyracksDataException: 1
org.apache.hyracks.api.exceptions.HyracksException: Job failed on account of:
HYR0002: org.apache.hyracks.api.exceptions.HyracksDataException: 1

at org.apache.hyracks.control.cc.job.JobRun.waitForCompletion(JobRun.java:212)
at org.apache.hyracks.control.cc.work.WaitForJobCompletionWork$1.run(WaitForJobCompletionWork.java:48)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.hyracks.api.exceptions.HyracksDataException: HYR0002: org.apache.hyracks.api.exceptions.HyracksDataException: 1
    at org.apache.hyracks.control.common.utils.ExceptionUtils.setNodeIds(ExceptionUtils.java:62)
    at org.apache.hyracks.control.nc.Task.run(Task.java:331)
    ... 3 more
Caused by: org.apache.hyracks.api.exceptions.HyracksDataException: org.apache.hyracks.api.exceptions.HyracksDataException: 1
    at org.apache.hyracks.api.rewriter.runtime.SuperActivityOperatorNodePushable.runInParallel(SuperActivityOperatorNodePushable.java:228)
    at org.apache.hyracks.api.rewriter.runtime.SuperActivityOperatorNodePushable.initialize(SuperActivityOperatorNodePushable.java:84)
    at org.apache.hyracks.control.nc.Task.run(Task.java:274)
    ... 3 more
Caused by: java.util.concurrent.ExecutionException: org.apache.hyracks.api.exceptions.HyracksDataException: 1
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at org.apache.hyracks.api.rewriter.runtime.SuperActivityOperatorNodePushable.runInParallel(SuperActivityOperatorNodePushable.java:222)
    ... 5 more
Caused by: org.apache.hyracks.api.exceptions.HyracksDataException: 1
    at org.apache.hyracks.storage.am.common.dataflow.IndexSearchOperatorNodePushable.close(IndexSearchOperatorNodePushable.java:206)
    at org.apache.hyracks.algebricks.runtime.operators.std.EmptyTupleSourceRuntimeFactory$1.close(EmptyTupleSourceRuntimeFactory.java:60)
    at org.apache.hyracks.algebricks.runtime.operators.meta.AlgebricksMetaOperatorDescriptor$1.initialize(AlgebricksMetaOperatorDescriptor.java:116)
    at org.apache.hyracks.api.rewriter.runtime.SuperActivityOperatorNodePushable.lambda$initialize$0(SuperActivityOperatorNodePushable.java:86)
    at org.apache.hyracks.api.rewriter.runtime.SuperActivityOperatorNodePushable.lambda$runInParallel$2(SuperActivityOperatorNodePushable.java:216)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    ... 3 more
    Suppressed: java.lang.ArrayIndexOutOfBoundsException: 1
        at org.apache.hyracks.dataflow.common.data.partition.FieldHashPartitionComputerFamily$1.partition(FieldHashPartitionComputerFamily.java:52)
        at org.apache.hyracks.dataflow.std.group.HashSpillableTableFactory$1.insert(HashSpillableTableFactory.java:145)
        at org.apache.hyracks.dataflow.std.group.external.ExternalHashGroupBy.insert(ExternalHashGroupBy.java:53)
        at org.apache.hyracks.dataflow.std.group.external.ExternalGroupBuildOperatorNodePushable.nextFrame(ExternalGroupBuildOperatorNodePushable.java:99)
        at org.apache.hyracks.dataflow.common.comm.io.AbstractFrameAppender.write(AbstractFrameAppender.java:92)
        at org.apache.hyracks.dataflow.common.comm.util.FrameUtils.appendProjectionToWriter(FrameUtils.java:235)
        at org.apache.hyracks.algebricks.runtime.operators.base.AbstractOneInputOneOutputOneFramePushRuntime.appendProjectionToFrame(AbstractOneInputOneOutputOneFramePushRuntime.java:95)
        at org.apache.hyracks.algebricks.runtime.operators.base.AbstractOneInputOneOutputOneFramePushRuntime.appendProjectionToFrame(AbstractOneInputOneOutputOneFramePushRuntime.java:90)
        at org.apache.hyracks.algebricks.runtime.operators.std.StreamProjectRuntimeFactory$1.nextFrame(StreamProjectRuntimeFactory.java:77)
        at org.apache.hyracks.algebricks.runtime.operators.meta.AlgebricksMetaOperatorDescriptor$2.nextFrame(AlgebricksMetaOperatorDescriptor.java:148)
        at org.apache.hyracks.dataflow.common.comm.io.AbstractFrameAppender.write(AbstractFrameAppender.java:92)
        at org.apache.hyracks.dataflow.std.join.InMemoryHashJoin.closeJoin(InMemoryHashJoin.java:156)
        at org.apache.hyracks.dataflow.std.join.OptimizedHybridHashJoin.closeProbe(OptimizedHybridHashJoin.java:409)
        at org.apache.hyracks.dataflow.std.join.OptimizedHybridHashJoinOperatorDescriptor$ProbeAndJoinActivityNode$1.close(OptimizedHybridHashJoinOperatorDescriptor.java:408)
        at org.apache.hyracks.algebricks.runtime.operators.base.AbstractOneInputOneOutputOneFramePushRuntime.close(AbstractOneInputOneOutputOneFramePushRuntime.java:57)
        at org.apache.hyracks.algebricks.runtime.operators.std.StreamSelectRuntimeFactory$1.close(StreamSelectRuntimeFactory.java:127)
        at org.apache.hyracks.algebricks.runtime.operators.meta.AlgebricksMetaOperatorDescriptor$2.close(AlgebricksMetaOperatorDescriptor.java:153)
        at org.apache.hyracks.storage.am.common.dataflow.IndexSearchOperatorNodePushable.close(IndexSearchOperatorNodePushable.java:230)
        ... 8 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
    at org.apache.hyracks.dataflow.common.data.partition.FieldHashPartitionComputerFamily$1.partition(FieldHashPartitionComputerFamily.java:52)
    at org.apache.hyracks.dataflow.std.group.HashSpillableTableFactory$1.insert(HashSpillableTableFactory.java:145)
    at org.apache.hyracks.dataflow.std.group.external.ExternalHashGroupBy.insert(ExternalHashGroupBy.java:53)
    at org.apache.hyracks.dataflow.std.group.external.ExternalGroupBuildOperatorNodePushable.nextFrame(ExternalGroupBuildOperatorNodePushable.java:99)
    at org.apache.hyracks.dataflow.common.comm.io.AbstractFrameAppender.write(AbstractFrameAppender.java:92)
    at org.apache.hyracks.dataflow.common.comm.util.FrameUtils.appendProjectionToWriter(FrameUtils.java:235)
    at org.apache.hyracks.algebricks.runtime.operators.base.AbstractOneInputOneOutputOneFramePushRuntime.appendProjectionToFrame(AbstractOneInputOneOutputOneFramePushRuntime.java:95)
    at org.apache.hyracks.algebricks.runtime.operators.base.AbstractOneInputOneOutputOneFramePushRuntime.appendProjectionToFrame(AbstractOneInputOneOutputOneFramePushRuntime.java:90)
    at org.apache.hyracks.algebricks.runtime.operators.std.StreamProjectRuntimeFactory$1.nextFrame(StreamProjectRuntimeFactory.java:77)
    at org.apache.hyracks.algebricks.runtime.operators.meta.AlgebricksMetaOperatorDescriptor$2.nextFrame(AlgebricksMetaOperatorDescriptor.java:148)
    at org.apache.hyracks.dataflow.common.comm.io.AbstractFrameAppender.write(AbstractFrameAppender.java:92)
    at org.apache.hyracks.dataflow.common.comm.util.FrameUtils.appendConcatToWriter(FrameUtils.java:187)
    at org.apache.hyracks.dataflow.std.join.InMemoryHashJoin.appendToResult(InMemoryHashJoin.java:176)
    at org.apache.hyracks.dataflow.std.join.InMemoryHashJoin.join(InMemoryHashJoin.java:135)
    at org.apache.hyracks.dataflow.std.join.InMemoryHashJoin.join(InMemoryHashJoin.java:151)
    at org.apache.hyracks.dataflow.std.join.OptimizedHybridHashJoin.probe(OptimizedHybridHashJoin.java:361)
    at org.apache.hyracks.dataflow.std.join.OptimizedHybridHashJoinOperatorDescriptor$ProbeAndJoinActivityNode$1.nextFrame(OptimizedHybridHashJoinOperatorDescriptor.java:397)
    at org.apache.hyracks.dataflow.common.comm.io.AbstractFrameAppender.write(AbstractFrameAppender.java:92)
    at org.apache.hyracks.dataflow.common.comm.util.FrameUtils.appendProjectionToWriter(FrameUtils.java:235)
    at org.apache.hyracks.algebricks.runtime.operators.base.AbstractOneInputOneOutputOneFramePushRuntime.appendProjectionToFrame(AbstractOneInputOneOutputOneFramePushRuntime.java:95)
    at org.apache.hyracks.algebricks.runtime.operators.base.AbstractOneInputOneOutputOneFramePushRuntime.appendProjectionToFrame(AbstractOneInputOneOutputOneFramePushRuntime.java:90)
    at org.apache.hyracks.algebricks.runtime.operators.std.StreamProjectRuntimeFactory$1.nextFrame(StreamProjectRuntimeFactory.java:77)
    at org.apache.hyracks.dataflow.common.comm.io.AbstractFrameAppender.write(AbstractFrameAppender.java:92)
    at org.apache.hyracks.dataflow.common.comm.io.FrameFixedFieldTupleAppender.write(FrameFixedFieldTupleAppender.java:146)
    at org.apache.hyracks.dataflow.common.comm.util.FrameUtils.appendToWriter(FrameUtils.java:138)
    at org.apache.hyracks.algebricks.runtime.operators.base.AbstractOneInputOneOutputOneFramePushRuntime.appendTupleToFrame(AbstractOneInputOneOutputOneFramePushRuntime.java:102)
    at org.apache.hyracks.algebricks.runtime.operators.std.StreamSelectRuntimeFactory$1.nextFrame(StreamSelectRuntimeFactory.java:147)
    at org.apache.hyracks.algebricks.runtime.operators.meta.AlgebricksMetaOperatorDescriptor$2.nextFrame(AlgebricksMetaOperatorDescriptor.java:148)
    at org.apache.hyracks.dataflow.common.comm.io.AbstractFrameAppender.write(AbstractFrameAppender.java:92)
    at org.apache.hyracks.storage.am.common.dataflow.IndexSearchOperatorNodePushable.close(IndexSearchOperatorNodePushable.java:203)
    ... 8 more
```

**NC Logs**

```
`INFO: Initializing TAID:TID:ANID:ODID:8:0:0:0 -> [org.apache.hyracks.storage.am.btree.dataflow.BTreeSearchOperatorDescriptor@37c29119, org.apache.hyracks.dataflow.std.join.OptimizedHybridHashJoinOperatorDescriptor$ProbeAndJoinActivityNode@f0c297e, org.apache.hyracks.dataflow.std.group.external.ExternalGroupOperatorDescriptor$AggregateActivity@24b683b, Asterix { 
  ets;
}, Asterix { 
  stream-select org.apache.asterix.runtime.evaluators.comparisons.EqualsDescriptor$_EvaluatorFactoryGen@1a7ef220;
  stream-project [0];
}, Asterix { 
  stream-project [1, 2, 3, 5, 6];
}]
org.apache.hyracks.api.exceptions.HyracksDataException: org.apache.hyracks.api.exceptions.HyracksDataException: 1
    at org.apache.hyracks.api.rewriter.runtime.SuperActivityOperatorNodePushable.runInParallel(SuperActivityOperatorNodePushable.java:228)
    at org.apache.hyracks.api.rewriter.runtime.SuperActivityOperatorNodePushable.initialize(SuperActivityOperatorNodePushable.java:84)
    at org.apache.hyracks.control.nc.Task.run(Task.java:274)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: org.apache.hyracks.api.exceptions.HyracksDataException: 1
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at org.apache.hyracks.api.rewriter.runtime.SuperActivityOperatorNodePushable.runInParallel(SuperActivityOperatorNodePushable.java:222)
    ... 5 more
Caused by: org.apache.hyracks.api.exceptions.HyracksDataException: 1
    at org.apache.hyracks.storage.am.common.dataflow.IndexSearchOperatorNodePushable.close(IndexSearchOperatorNodePushable.java:206)
    at org.apache.hyracks.algebricks.runtime.operators.std.EmptyTupleSourceRuntimeFactory$1.close(EmptyTupleSourceRuntimeFactory.java:60)
    at org.apache.hyracks.algebricks.runtime.operators.meta.AlgebricksMetaOperatorDescriptor$1.initialize(AlgebricksMetaOperatorDescriptor.java:116)
    at org.apache.hyracks.api.rewriter.runtime.SuperActivityOperatorNodePushable.lambda$initialize$0(SuperActivityOperatorNodePushable.java:86)
    at org.apache.hyracks.api.rewriter.runtime.SuperActivityOperatorNodePushable.lambda$runInParallel$2(SuperActivityOperatorNodePushable.java:216)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    ... 3 more
    Suppressed: java.lang.ArrayIndexOutOfBoundsException: 1
        at org.apache.hyracks.dataflow.common.data.partition.FieldHashPartitionComputerFamily$1.partition(FieldHashPartitionComputerFamily.java:52)
        at org.apache.hyracks.dataflow.std.group.HashSpillableTableFactory$1.insert(HashSpillableTableFactory.java:145)
        at org.apache.hyracks.dataflow.std.group.external.ExternalHashGroupBy.insert(ExternalHashGroupBy.java:53)
        at org.apache.hyracks.dataflow.std.group.external.ExternalGroupBuildOperatorNodePushable.nextFrame(ExternalGroupBuildOperatorNodePushable.java:99)
        at org.apache.hyracks.dataflow.common.comm.io.AbstractFrameAppender.write(AbstractFrameAppender.java:92)
        at org.apache.hyracks.dataflow.common.comm.util.FrameUtils.appendProjectionToWriter(FrameUtils.java:235)
        at org.apache.hyracks.algebricks.runtime.operators.base.AbstractOneInputOneOutputOneFramePushRuntime.appendProjectionToFrame(AbstractOneInputOneOutputOneFramePushRuntime.java:95)
        at org.apache.hyracks.algebricks.runtime.operators.base.AbstractOneInputOneOutputOneFramePushRuntime.appendProjectionToFrame(AbstractOneInputOneOutputOneFramePushRuntime.java:90)
        at org.apache.hyracks.algebricks.runtime.operators.std.StreamProjectRuntimeFactory$1.nextFrame(StreamProjectRuntimeFactory.java:77)
        at org.apache.hyracks.algebricks.runtime.operators.meta.AlgebricksMetaOperatorDescriptor$2.nextFrame(AlgebricksMetaOperatorDescriptor.java:148)
        at org.apache.hyracks.dataflow.common.comm.io.AbstractFrameAppender.write(AbstractFrameAppender.java:92)
        at org.apache.hyracks.dataflow.std.join.InMemoryHashJoin.closeJoin(InMemoryHashJoin.java:156)
        at org.apache.hyracks.dataflow.std.join.OptimizedHybridHashJoin.closeProbe(OptimizedHybridHashJoin.java:409)
        at org.apache.hyracks.dataflow.std.join.OptimizedHybridHashJoinOperatorDescriptor$ProbeAndJoinActivityNode$1.close(OptimizedHybridHashJoinOperatorDescriptor.java:408)
        at org.apache.hyracks.algebricks.runtime.operators.base.AbstractOneInputOneOutputOneFramePushRuntime.close(AbstractOneInputOneOutputOneFramePushRuntime.java:57)
        at org.apache.hyracks.algebricks.runtime.operators.std.StreamSelectRuntimeFactory$1.close(StreamSelectRuntimeFactory.java:127)
        at org.apache.hyracks.algebricks.runtime.operators.meta.AlgebricksMetaOperatorDescriptor$2.close(AlgebricksMetaOperatorDescriptor.java:153)
        at org.apache.hyracks.storage.am.common.dataflow.IndexSearchOperatorNodePushable.close(IndexSearchOperatorNodePushable.java:230)
        ... 8 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
    at org.apache.hyracks.dataflow.common.data.partition.FieldHashPartitionComputerFamily$1.partition(FieldHashPartitionComputerFamily.java:52)
    at org.apache.hyracks.dataflow.std.group.HashSpillableTableFactory$1.insert(HashSpillableTableFactory.java:145)
    at org.apache.hyracks.dataflow.std.group.external.ExternalHashGroupBy.insert(ExternalHashGroupBy.java:53)
    at org.apache.hyracks.dataflow.std.group.external.ExternalGroupBuildOperatorNodePushable.nextFrame(ExternalGroupBuildOperatorNodePushable.java:99)
    at org.apache.hyracks.dataflow.common.comm.io.AbstractFrameAppender.write(AbstractFrameAppender.java:92)
    at org.apache.hyracks.dataflow.common.comm.util.FrameUtils.appendProjectionToWriter(FrameUtils.java:235)
    at org.apache.hyracks.algebricks.runtime.operators.base.AbstractOneInputOneOutputOneFramePushRuntime.appendProjectionToFrame(AbstractOneInputOneOutputOneFramePushRuntime.java:95)
    at org.apache.hyracks.algebricks.runtime.operators.base.AbstractOneInputOneOutputOneFramePushRuntime.appendProjectionToFrame(AbstractOneInputOneOutputOneFramePushRuntime.java:90)
    at org.apache.hyracks.algebricks.runtime.operators.std.StreamProjectRuntimeFactory$1.nextFrame(StreamProjectRuntimeFactory.java:77)
    at org.apache.hyracks.algebricks.runtime.operators.meta.AlgebricksMetaOperatorDescriptor$2.nextFrame(AlgebricksMetaOperatorDescriptor.java:148)
    at org.apache.hyracks.dataflow.common.comm.io.AbstractFrameAppender.write(AbstractFrameAppender.java:92)
    at org.apache.hyracks.dataflow.common.comm.util.FrameUtils.appendConcatToWriter(FrameUtils.java:187)
    at org.apache.hyracks.dataflow.std.join.InMemoryHashJoin.appendToResult(InMemoryHashJoin.java:176)
    at org.apache.hyracks.dataflow.std.join.InMemoryHashJoin.join(InMemoryHashJoin.java:135)
    at org.apache.hyracks.dataflow.std.join.InMemoryHashJoin.join(InMemoryHashJoin.java:151)
    at org.apache.hyracks.dataflow.std.join.OptimizedHybridHashJoin.probe(OptimizedHybridHashJoin.java:361)
    at org.apache.hyracks.dataflow.std.join.OptimizedHybridHashJoinOperatorDescriptor$ProbeAndJoinActivityNode$1.nextFrame(OptimizedHybridHashJoinOperatorDescriptor.java:397)
    at org.apache.hyracks.dataflow.common.comm.io.AbstractFrameAppender.write(AbstractFrameAppender.java:92)
    at org.apache.hyracks.dataflow.common.comm.util.FrameUtils.appendProjectionToWriter(FrameUtils.java:235)
    at org.apache.hyracks.algebricks.runtime.operators.base.AbstractOneInputOneOutputOneFramePushRuntime.appendProjectionToFrame(AbstractOneInputOneOutputOneFramePushRuntime.java:95)
    at org.apache.hyracks.algebricks.runtime.operators.base.AbstractOneInputOneOutputOneFramePushRuntime.appendProjectionToFrame(AbstractOneInputOneOutputOneFramePushRuntime.java:90)
    at org.apache.hyracks.algebricks.runtime.operators.std.StreamProjectRuntimeFactory$1.nextFrame(StreamProjectRuntimeFactory.java:77)
    at org.apache.hyracks.dataflow.common.comm.io.AbstractFrameAppender.write(AbstractFrameAppender.java:92)
    at org.apache.hyracks.dataflow.common.comm.io.FrameFixedFieldTupleAppender.write(FrameFixedFieldTupleAppender.java:146)
    at org.apache.hyracks.dataflow.common.comm.util.FrameUtils.appendToWriter(FrameUtils.java:138)
    at org.apache.hyracks.algebricks.runtime.operators.base.AbstractOneInputOneOutputOneFramePushRuntime.appendTupleToFrame(AbstractOneInputOneOutputOneFramePushRuntime.java:102)
    at org.apache.hyracks.algebricks.runtime.operators.std.StreamSelectRuntimeFactory$1.nextFrame(StreamSelectRuntimeFactory.java:147)
    at org.apache.hyracks.algebricks.runtime.operators.meta.AlgebricksMetaOperatorDescriptor$2.nextFrame(AlgebricksMetaOperatorDescriptor.java:148)
    at org.apache.hyracks.dataflow.common.comm.io.AbstractFrameAppender.write(AbstractFrameAppender.java:92)
    at org.apache.hyracks.storage.am.common.dataflow.IndexSearchOperatorNodePushable.close(IndexSearchOperatorNodePushable.java:203)
    ... 8 more`
```

**Comment by pouriapirz** [comment]
The query works fine without hash hint for group-by.

**Comment by pouriapirz** [comment]
Below issue created to follow-up:

https://issues.apache.org/jira/browse/ASTERIXDB-1727
